### ISSUE TITLE
Tag and release

### ISSUE THREAD

**Issue by BassemN** [rguliev/conditionize2.js#4]
Hello,

Many thanks for the new updates :+1: 

Could you please create a tag like 1.0.0 for the first release? so we can add a change log for each tag.

Thanks

**Comment by rguliev** [comment]
Hi,
You are welcome!
Sure, sounds great. A added a 2.0.0 tag since it is conditionize**2**.js and in package.json it is 2.0.0 as well.
Thanks for the suggestion.

**Comment by BassemN** [comment]
Great. Now for the CDN version on the readme set the URL to be 
```
https://cdn.jsdelivr.net/gh/rguliev/conditionize2.js@2.0.0/jquery.conditionize2.min.js
```
Thanks again
