### ISSUE TITLE
NPM Module

### ISSUE THREAD

**Issue by landwire** [rguliev/conditionize2.js#7]
Do you know roughly when you will be able to publish the code as an NPM module? I have seen it is in planning, but it would be good to get a rough idea about the timeframe.

**Comment by rguliev** [comment]
Hi,
Sorry, I was a bit busy on other projects. It's most probable to be in November. Before publishing the code, I need to more accurately define a dependency on the jQuery version. I guess that will take the most time. If you want to help with that - you are welcome!:)

**Comment by BassemN** [comment]
@landwire  For now, you can use the following command to install this library via npm directly from GitHub
```
npm install github:rguliev/conditionize2.js
```

**Comment by rguliev** [comment]
@BassemN Thanks!)

**Comment by rguliev** [comment]
I'm sorry for the delay.
I wanted to clarify the jQuery dependency before publishing on npm. Now, with automated testing, I checked all available jQuery versions and [published the package on npm](https://www.npmjs.com/package/conditionize2). It can be installed by `npm i conditionize2`

**Comment by BassemN** [comment]
@rguliev Thanks a lot
