### ISSUE TITLE
it's getting slow and slow and stuck on few place 

### ISSUE THREAD

**Issue by hemant17** [rguliev/conditionize2.js#9]
https://nextlevelbot.com/syntaxgenerator
as you can see on the site when you type in the trading symbol box and  auto strike price it's getting slow and get stuck 
is there any way I can optimize it?

**Comment by rguliev** [comment]
I would say there is a problem with your code because it does not seem to be a too "loaded" condition.

I'm closing this issue since it does not seem to be related to the package itself.
